version: "3.2"

services:

    grafana:
        image: grafana/grafana:4.4.3
        hostname: grafana
        networks:
            - afrontend
            - backend 
        environment:
            GF_SERVER_ROOT_URL: "http://db_influxdb"
            GF_SECURITY_ADMIN_PASSWORD: "mysecretpassword"
            GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-clock-panel"
        volumes:
          - type: bind
            source: /mnt/shared_data/grafana
            target: /var/lib/grafana
        deploy:
            replicas: 1
            labels:
                - "traefik.port=3000"
                - "traefik.frontend.entryPoints=http"
                - "traefik.frontend.rule=Host:grafana.docker.ptechtoolz.com"
                - "traefik.docker.network=afrontend"

            
networks:
    afrontend:
        external: true
    backend:
        external: true
