version: "3.1"

services:

    influxdb:
        image: influxdb:1.2.4
        hostname: influxdb
        networks:
            - backend 
        environment:
            INFLUXDB_ADMIN_ENABLED: "true"
        volumes:
          - type: bind
            source: /mnt/shared_data/ltsdata/influxdb
            target: /var/lib/influxdb
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 1g

            
networks:
    backend:
        external: true
