version: "3.1"

services:

    postgresql:
        image: postgres:9.6 
        hostname: postgres
        networks:
            - backend 
        environment:
            POSTGRES_PASSWORD: "mysecretpassword"
        volumes:
          - type: bind
            source: /mnt/shared_data/ltsdata/pgdata
            target: /var/lib/postgresql/data
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 1g
                # reservations:
                    # cpus: "0.5"
                     #memory: 512mb
            #placement:
                #constraints: [node.role == manager]

            
networks:
    backend:
        external: true

