version: "3.2"

services:

    redis:
        image: redis:3.2.10
        hostname: redis
        networks:
            - backend 
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 1g

            
networks:
    backend:
        external: true

