version: "3.1"

services:

    #this is technically all that's needed for the bot trader. Contains data for all markets
    #for redundancy, this is ran in a separate container from the order-scraper
    summary-scraper:
        image: meetri/cryptocoin:latest
        hostname: crypto-scraper
        networks:
            - backend 
        environment:
            DEBUGMODE: "true"
            GET_MARKET_SUMMARY: "true"
            JOB: "nodejs_websocket"
            #force exit the container to refresh websocket connection
            FORCE_EXIT: 30
            QUEUE: "marketqueue"
            TA_INTERVAL: 30000
            INFLUXDB_HOST: "db_influxdb"
            REDIS_HOST: "db_redis"
            REDIS_PORT: 6379
            PGHOST: "db_postgresql"
            PGPASSWORD: ${PGPASSWORD}
            bittrex_key: ${BITTREX_KEY}
            bittrex_secret: ${BITTREX_SECRET}
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512mb


    #for faster updates add currency pair to the market_list
    order-scraper:
        image: meetri/cryptocoin:latest
        hostname: crypto-scraper
        networks:
            - backend 
        environment:
            DEBUGMODE: "true"
            GET_MARKET_ORDERS: "true"
            MARKET_LIST: USDT-BTC USDT-ETH USDT-LTC USDT-XRP BTC-ETH BTC-XRP BTC-LTC 
            JOB: "nodejs_websocket"
            FORCE_EXIT: 30
            QUEUE: "marketqueue"
            TA_INTERVAL: 30000
            INFLUXDB_HOST: "db_influxdb"
            REDIS_HOST: "db_redis"
            REDIS_PORT: 6379
            PGHOST: "db_postgresql"
            PGPASSWORD: ${PGPASSWORD}
            bittrex_key: ${BITTREX_KEY}
            bittrex_secret: ${BITTREX_SECRET}
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 512mb


    #get market data from redis and do bulk writes to influxdb
    coin-saver:
        image: meetri/cryptocoin:latest
        hostname: crypto-scraper
        networks:
            - backend 
        environment:
            JOB: "save_marketdata"
            QUEUE: "marketqueue"
            WORKERS: 10
            TA_WORKERS: 0
            INFLUXDB_HOST: "db_influxdb"
            REDIS_HOST: "db_redis"
            REDIS_PORT: 6379
            PGHOST: "db_postgresql"
            PGPASSWORD: "abignewworld"
            bittrex_key: ${BITTREX_KEY}
            bittrex_secret: ${BITTREX_SECRET}
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "1"
                    memory: 1g

            
networks:
    backend:
        external: true

