version: "3.1"

services:

    grafana:
        image: grafana/grafana:4.4.3
        hostname: grafana
        networks:
            - backend 
        environment:
            GF_SERVER_ROOT_URL: "http://db_influxdb"
            GF_SECURITY_ADMIN_PASSWORD: "nimda"
            GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-clock-panel"
            POSTGRES_PASSWORD: ${PGPASSWORD}
        volumes:
            - "data:/var/lib/grafana"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

            
networks:
    backend:
        external: true

volumes:
    data: 
        driver: local-persist
        driver_opts:
            mountpoint: /mnt/data/ltsdata/grafana

