version: "3.1"

services:

    influxdb:
        image: influxdb:1.2.4
        hostname: influxdb
        networks:
            - backend 
        environment:
            INFLUXDB_ADMIN_ENABLED: "true"
        volumes:
            - "influxdb-data:/var/lib/influxdb"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            resources:
                limits:
                    cpus: "1"
                    memory: 1g
                reservations:
                    cpus: "0.5"
                    memory: 512mb
            placement:
                constraints: [node.role == manager]

            
networks:
    backend:
        external: true

volumes:
    influxdb-data: 
        driver: local-persist
        driver_opts:
            mountpoint: /mnt/shared_data/ltsdata/influxdb

